# Generated by Django 4.0 on 2022-05-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('desc', models.CharField(max_length=525, verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
