# Generated by Django 4.0 on 2022-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_aboutmemodel_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmemodel',
            name='desc',
            field=models.CharField(max_length=525, verbose_name='Description'),
        ),
    ]
