# Generated by Django 4.0 on 2022-06-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_knowledgesmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('email', models.EmailField(max_length=128, verbose_name='Email')),
                ('subject', models.CharField(max_length=24, verbose_name='Subject')),
                ('message', models.CharField(max_length=780, verbose_name='Message')),
            ],
            options={
                'verbose_name': 'UsersMessages',
            },
        ),
    ]
